version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_cars
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sgt2023
      MYSQL_DATABASE: car_db
   #   MYSQL_USER: julija.andrusenko
   #  MYSQL_PASSWORD: sgt2023
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      mysql-network:
        aliases:
          - mysql
  python:
    build: .
    container_name: python_cars
    depends_on:
      - mysql
    restart: always
    ports:
      - "5000:5000"
    networks:
      - mysql-network

networks:
  mysql-network:
      driver: bridge
volumes:
  mysql-data:
    driver: local
