version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_cars
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sgt2023
      MYSQL_DATABASE: car_db
    ports:
      - '3308:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

  app:
    build: .
    container_name: python_cars
    depends_on:
      - mysql
    restart: always
    ports:
      - '8000:8000'
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local