- name: "run apt update"
  apt:
    name: '*'
    state: latest

- name: "AWS - Install docker"
  hosts: aws-docker-vms
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes
